name: Test Report

on:
  workflow_run:
    workflows: ['CI']
    types:
      - completed

permissions: write-all

jobs:
  report:
    name: Workflow test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create test report
        uses: ./
        with:
          artifact: test-results
          name: Workflow Report
          path: '*.xml'
          reporter: jest-junit

      - name: Create mochawesome report
        uses: ./
        if: success() || failure()
        with:
          name: Mochawesome Tests
          path: __tests__/fixtures/mochawesome-json.json
          reporter: mochawesome-json
          fail-on-error: false
